version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'your-github-username'
    assignees:
      - 'your-github-username'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    # メジャー更新のみを検出するように全グループを変更
    groups:
      storybook-dependencies:
        patterns:
          - '@storybook/*'
          - 'storybook'
        update-types: ['major']  # minor/patchから変更
      testing-dependencies:
        patterns:
          - '@testing-library/*'
          - '@vitest/*'
          - 'vitest'
          - 'jsdom'
        update-types: ['major']  # minor/patchから変更
      eslint-dependencies:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
        update-types: ['major']  # minor/patchから変更
      react-ecosystem:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
        update-types: ['major']  # minor/patchから変更
      # 新しいグループ: その他全ての依存関係をメジャー更新のみ対象に
      all-dependencies:
        patterns: ['*']
        update-types: ['major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    commit-message:
      prefix: 'chore(actions)'
    # GitHub Actionsもメジャー更新のみに制限
    groups:
      actions-dependencies:
        patterns: ['*']
        update-types: ['major']
