# .gemini/config.yaml

# Disables fun features such as a poem in the initial pull request summary.
have_fun: false

code_review:
  # Set to true to disable Gemini from acting on pull requests.
  disable: false

  # The minimum severity of review comments to consider.
  # Options: LOW, MEDIUM, HIGH, CRITICAL
  comment_severity_threshold: MEDIUM

  # The maximum number of review comments to post. Use -1 for unlimited.
  max_review_comments: -1

  # Configuration for pull request opened events.
  pull_request_opened:
    # Posts a help message on pull request open.
    help: false
    # Posts a pull request summary on the pull request open.
    summary: true
    # Posts a code review on pull request open.
    code_review: true

# A list of glob patterns for files and directories that Gemini should ignore.
ignore_patterns:
  - 'dist/**'
  - '.next/**'
  - 'node_modules/**'
  - 'package-lock.json'
  - 'pnpm-lock.yaml'
